variable "kubeconfig" {}
variable "namespace" {}
variable "number_of_hosts" {}
variable "prefix" {}
variable "cpu" {}
variable "memory" {}
variable "run_strategy" {}
//variable "hostname" {}
variable "machine_type" {}
variable "nic_name" {}
variable "nic_network" {}
variable "ssh_public_key" {}
variable "ssh_user" {}
variable "disk1" {}
variable "extradisks" {}
variable "user_data" {}
variable "network_data" {}